stages:
  - release

release:
  image: node:lts
  stage: release
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'

  before_script:
    - npm ci

  script:
    - npx semantic-release

  variables:
    GITLAB_TOKEN: $GITLAB_TOKEN
