stages:
  - release

release:
  image: node:lts
  stage: release
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'

  before_script:
    - npm install -g semantic-release
    - npm install -g @semantic-release/changelog @semantic-release/git @semantic-release/gitlab

  script:
    - npx semantic-release

  variables:
    GITLAB_TOKEN: $GITLAB_TOKEN
