trigger:
  branches:
    include:
      - main

pr: none

pool:
  vmImage: ubuntu-latest

steps:
  - checkout: self
    fetchDepth: 0
    persistCredentials: true

  - task: NodeTool@0
    inputs:
      versionSpec: "lts/*"
    displayName: "Setup Node.js"

  - script: |
      npm ci
    displayName: "Install release tools"

  - script: npx semantic-release
    displayName: "Release"
    env:
      SYSTEM_ACCESSTOKEN: $(System.AccessToken)
